name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: join test
        env:
          MESSAGE: ${{ toJson(join(github.event.commits.*.message)) }}
        run: echo "$MESSAGE"
      - name: true or false
        env:
          RESULT: ${{ toJson(contains(join(github.event.commits.*.message)), '#skip') }}
        run: echo "$RESULT"